import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Navbar } from "./components/Navbar";
import { BoltIcon, House, Mars } from "lucide-react";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <Providers>
          <Navbar />
          <main className="grow overflow-auto">
            {children}
          </main>
          <footer className="grid grid-cols-3">
            <button className="flex items-center justify-center p-4 hover:bg-slate-900 cursor-pointer transition-all ease-in-out duration-250"><House /></button>
            <button className="flex items-center justify-center p-4"><Mars /></button>
            <button className="flex items-center justify-center p-4"><BoltIcon /></button>
          </footer>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
